# 1. List and set comprehensions

In [9]:
compr_list = [i for i in range(0, 10)]

In [24]:
compr_list_str = "Зродились ми великої години з пожеж війни і полум'я вогнів"

In [25]:
[symbol for symbol in compr_list_str]

['З',
 'р',
 'о',
 'д',
 'и',
 'л',
 'и',
 'с',
 'ь',
 ' ',
 'м',
 'и',
 ' ',
 'в',
 'е',
 'л',
 'и',
 'к',
 'о',
 'ї',
 ' ',
 'г',
 'о',
 'д',
 'и',
 'н',
 'и',
 ' ',
 'з',
 ' ',
 'п',
 'о',
 'ж',
 'е',
 'ж',
 ' ',
 'в',
 'і',
 'й',
 'н',
 'и',
 ' ',
 'і',
 ' ',
 'п',
 'о',
 'л',
 'у',
 'м',
 "'",
 'я',
 ' ',
 'в',
 'о',
 'г',
 'н',
 'і',
 'в']

In [26]:
compr_set_1 = {i for i in range(0, 10)}

In [27]:
print(compr_set_1)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


In [28]:
compr_set_2 = {[i] for i in range(0, 10)}

TypeError: unhashable type: 'list'

In [ ]:
print(compr_set_2)

In [31]:
compr_set_3 = {(i,) for i in range(0, 10)}

In [32]:
print(compr_set_3)

{(6,), (2,), (5,), (8,), (4,), (1,), (7,), (0,), (3,), (9,)}


In [43]:
tuple(i for i in range(0, 10))

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [50]:
action_list_compr = [(m, m**2) if m%3==0 else (m, m**3) for m in range(1,101) if m == 20]

In [51]:
action_list_compr

[(20, 8000)]

# 2. Трошки про itertools і zip

In [52]:
import itertools

In [60]:
a = [1,2,3,4,5]
b = [6,7,8,9,10,11,12]

In [55]:
lazy_compr = (i for i in range(0, 10))

In [54]:
itertools.product(a, b)

In [62]:
tuple(itertools.product(a, b))

((1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (1, 10),
 (1, 11),
 (1, 12),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (2, 10),
 (2, 11),
 (2, 12),
 (3, 6),
 (3, 7),
 (3, 8),
 (3, 9),
 (3, 10),
 (3, 11),
 (3, 12),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (4, 10),
 (4, 11),
 (4, 12),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (5, 10),
 (5, 11),
 (5, 12))

In [ ]:
list(itertools.product(a, b))

In [63]:
list(itertools.permutations(a))

[(1, 2, 3, 4, 5),
 (1, 2, 3, 5, 4),
 (1, 2, 4, 3, 5),
 (1, 2, 4, 5, 3),
 (1, 2, 5, 3, 4),
 (1, 2, 5, 4, 3),
 (1, 3, 2, 4, 5),
 (1, 3, 2, 5, 4),
 (1, 3, 4, 2, 5),
 (1, 3, 4, 5, 2),
 (1, 3, 5, 2, 4),
 (1, 3, 5, 4, 2),
 (1, 4, 2, 3, 5),
 (1, 4, 2, 5, 3),
 (1, 4, 3, 2, 5),
 (1, 4, 3, 5, 2),
 (1, 4, 5, 2, 3),
 (1, 4, 5, 3, 2),
 (1, 5, 2, 3, 4),
 (1, 5, 2, 4, 3),
 (1, 5, 3, 2, 4),
 (1, 5, 3, 4, 2),
 (1, 5, 4, 2, 3),
 (1, 5, 4, 3, 2),
 (2, 1, 3, 4, 5),
 (2, 1, 3, 5, 4),
 (2, 1, 4, 3, 5),
 (2, 1, 4, 5, 3),
 (2, 1, 5, 3, 4),
 (2, 1, 5, 4, 3),
 (2, 3, 1, 4, 5),
 (2, 3, 1, 5, 4),
 (2, 3, 4, 1, 5),
 (2, 3, 4, 5, 1),
 (2, 3, 5, 1, 4),
 (2, 3, 5, 4, 1),
 (2, 4, 1, 3, 5),
 (2, 4, 1, 5, 3),
 (2, 4, 3, 1, 5),
 (2, 4, 3, 5, 1),
 (2, 4, 5, 1, 3),
 (2, 4, 5, 3, 1),
 (2, 5, 1, 3, 4),
 (2, 5, 1, 4, 3),
 (2, 5, 3, 1, 4),
 (2, 5, 3, 4, 1),
 (2, 5, 4, 1, 3),
 (2, 5, 4, 3, 1),
 (3, 1, 2, 4, 5),
 (3, 1, 2, 5, 4),
 (3, 1, 4, 2, 5),
 (3, 1, 4, 5, 2),
 (3, 1, 5, 2, 4),
 (3, 1, 5, 4, 2),
 (3, 2, 1, 4, 5),
 (3, 2, 1,

In [68]:
c = [11, 12, 13, 14, 15, 16, 17, 18]

In [80]:
a = [1,1,1,2,3,4,5]
b = [6,7,8,9,10,11,12]

In [77]:
dict(zip(b, a))

{6: 1, 7: 2, 8: 3, 9: 4, 10: 5}

In [75]:
list(zip(a, b, c))

[(1, 6, 11), (2, 7, 12), (3, 8, 13), (4, 9, 14), (5, 10, 15)]

In [82]:
list(itertools.zip_longest(a, c))

[(1, 11), (1, 12), (1, 13), (2, 14), (3, 15), (4, 16), (5, 17), (None, 18)]

In [81]:
dict(itertools.zip_longest(a, c))

{1: 13, 2: 14, 3: 15, 4: 16, 5: 17, None: 18}

# 3. sum() і map()

In [105]:
a = [i**2 for i in range(0, 25)]

In [84]:
def cubes(x):
    return x**3

In [89]:
a = input("Введи число").split()

Введи число1 2 3 4 5


In [ ]:
list(map(int, input("Введи число")))

In [96]:
sum_var = 0

for i in a:
    sum_var += i

In [97]:
sum_var

90000

In [102]:
"".join(a)

'0123456789101112131415161718192021222324'

In [106]:
from math import sqrt

sqrt_list = map(sqrt, a)
str_list = map(str, a)

In [107]:
list(sqrt_list)

[0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0]

In [108]:
list(str_list)

['0',
 '1',
 '4',
 '9',
 '16',
 '25',
 '36',
 '49',
 '64',
 '81',
 '100',
 '121',
 '144',
 '169',
 '196',
 '225',
 '256',
 '289',
 '324',
 '361',
 '400',
 '441',
 '484',
 '529',
 '576']

# 4. NumPy (прекрасна документація лежить [тут](https://numpy.org/doc/stable/user/absolute_beginners.html))

In [109]:
import numpy as np

In [110]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [111]:
type(np.arange(5))

numpy.ndarray

In [114]:
type(np.arange(19)[4])

numpy.int64

In [115]:
np.array([1, 2, 3])

array([1, 2, 3])

In [112]:
np.zeros(2)

array([0., 0.])

In [113]:
type(np.zeros(4)[3])

numpy.float64

In [116]:
np.ones([10, 10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [117]:
np.linspace(0, 10, num=100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [118]:
np.ones([3, 3], dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# 5. Трохи про словники

In [120]:
employee_hierarchy = {
    "CEO":
    {
        "CTO":
        {
            "VP of Engineering":
            {
                "Project Manager 1":
                [
                    "Employee 1",
                    "Employee 2",
                    "Employee 3"
                ],
                "Project Manager 2":
                [
                    "Employee 1",
                    "Employee 2",
                    "Employee 3"
                ]

            },
            "VP of R&D":
            {
                "Research Manager 1":
                [
                    "Employee 1",
                    "Employee 2",
                    "Employee 3"
                ],
                "Research Manager 2":
                [
                    "Employee 1",
                    "Employee 2",
                    "Employee 3"
                ]

            },
        },
        "CMO":
        {
            "Brand Manager":
                ["SMM manager", "BTL manager", "ATL manager"]
        }
    }
}

In [124]:
employee_hierarchy["CEO"]["CTO"]["VP of R&D"]["Research Manager 1"]

['Employee 1', 'Employee 2', 'Employee 3']

In [125]:
movies_dataset = {
    "Avatar": 2047674,
    "Citizen Kane": 2858859,
}

In [ ]:
another_movie_dataset = [
    {'id': 645, 'name': 'James Bond Collection', 'poster_path': '/HORpg5CSkmeQlAolx3bKMrKgfi.jpg',
     'backdrop_path': '/6VcVl48kNKvdXOZfJPdarlUGOsk.jpg', "rank": 8},
    {'id': 117693, 'name': 'Balto Collection', 'poster_path': '/w0ZgH6Lgxt2bQYnf1ss74UvYftm.jpg',
     'backdrop_path': '/9VM5LiJV0bGb1st1KyHA3cVnO2G.jpg', "rank": 7},
    {'id': 136214, 'name': 'Pocahontas Collection', 'poster_path': '/s4RkDe4AjwyrlltdF6Ui7INlME6.jpg',
     'backdrop_path': '/qqeOxNmtAW7WXdbrmQftgluvve7.jpg', "rank": 10}
]


In [ ]:
{
    645: {'name': 'James Bond Collection', 'poster_path': '/HORpg5CSkmeQlAolx3bKMrKgfi.jpg',
     'backdrop_path': '/6VcVl48kNKvdXOZfJPdarlUGOsk.jpg', "rank": 8},
    117693: {'name': 'Balto Collection', 'poster_path': '/w0ZgH6Lgxt2bQYnf1ss74UvYftm.jpg',
     'backdrop_path': '/9VM5LiJV0bGb1st1KyHA3cVnO2G.jpg', "rank": 7},
}

In [127]:
a = {
    1: input("hey")
}

heyPryvit


In [130]:
def enter_film_data(id_num):
    return {
        "id": id_num,
        "name": input("Enter films name"),
        "director": input("Enter films director"),
        "rank": input("Enter films rank")
    }

Створити консольний застосунок для збереження інформації про фільми.

Застосунок має мати можливість робити наступне:

1. Створювати новий фільм в базі
2. Переглядати інформацію про фільм
3. Шукати фільм в базі
4. Оновлювати фільм в базі
5. Видаляти фільм з бази

# 1 крок: базові сутності, їхня структура та формат

Базова сутність - фільм.
Атрибути:

1. Назва
2. Жанр (опціонально)
3. Рік випуску
4. Режисер
5. Рейтинг IMDB
6. Склад акторів (опціонально)
7. Вікові обмеження (опціонально)
8. Тривалість (опціонально)
9. Компанія-виробник
10. Мова (опціонально)

# 2 крок: дії, котрі треба робити з базовою сутністю

Стандартний набір дій (CRUD)

# 3. Аналіз базових сутностей, типів даних і їх обмежень

    Назва: str
    Жанр (опціонально): List[str], max = 3
    Рік випуску: int > 0
    Режисер: str, only alphabet chars
    Рейтинг IMDB: float >= 0, round(2,1)
    Склад акторів (опціонально): List[str]
    Вікові обмеження (опціонально): str
    Тривалість (опціонально): int
    Мова (опціонально): str

# 4. Приклад реалізації базової сутності на Python

In [148]:
example_film_dict = {
    "id": 2,
    "name": "Аватар: Шлях води",
    "genres": ["Action"],
    "year": 2022,
    "director": "James Cameron",
    "imdb": 7.8,
}

example_film_dict_2 = {
    "id": 3,
    "name": "Аватар: Шлях води 3",
    "genres": ["Action"],
    "year": 2022,
    "director": "James Cameron",
    "imdb": 7.8,    
}

# 5. Загальний сценарій використання

1. Користувач обирає команду щоб виконати
2. Система вирішує, що зробити з базою фільмів згідно команди
3. Система запитує в користувача додаткові дані за потреби
4. Система видає якийсь очікуваний результат (дані про фільм, повідомлення про успішне створення фільму, повідомлення про успішне видалення фільму ітд)

# 6. Імплементація

In [154]:
{
    1: {
    "name": "Аватар: Шлях води",
    "genres": ["Action"],
    "year": 2022,
    "director": "James Cameron",
    "imdb": 7.8,
},
    2: {
    "name": "Аватар: Шлях води 3",
    "genres": ["Action"],
    "year": 2022,
    "director": "James Cameron",
    "imdb": 7.8,    
},
}

{1: {'name': 'Аватар: Шлях води',
  'genres': ['Action'],
  'year': 2022,
  'director': 'James Cameron',
  'imdb': 7.8},
 2: {'name': 'Аватар: Шлях води 3',
  'genres': ['Action'],
  'year': 2022,
  'director': 'James Cameron',
  'imdb': 7.8}}

In [156]:
lists_container = dict()

In [157]:
def create_film():
    pass

def update_film():
    pass

def delete_film():
    pass

def read_film():
    pass

In [196]:
new_dict = {
    "id": {
        1: {
            "name": "Avatar",
            "director": "James Cameron"
        },
        2: {
            "name": "Harry Potter",
            "director": "Chis Colambus"
        }
    }
}

In [197]:
new_dict["id"]

{1: {'name': 'Avatar', 'director': 'James Cameron'},
 2: {'name': 'Harry Potter', 'director': 'Chis Colambus'}}

Створимо головний фрагмент програми, де буде виконуватися логіка взаємодії з користувачем

In [175]:
def read_command_from_user():
    GREETING_TEXT = """Вітаю в системі для збереження даних про фільми."""


    commands_container = [command.lower() for command in ["create", "update", "read", "delete"]]

    print(GREETING_TEXT)
    print("Print help for help")

    while True:
        command = input("Введіть команду: ").lower()
        if command == "help":
            print("""Вам доступні наступні команди:""")
            for number, command in enumerate(commands_container):
                print(f"{number + 1}. {command}")
        elif command in commands_container:
            break
        else:
            print("Введена невалідна команда. Введіть, будь ласка, команду ще раз")
    return command

In [186]:
def menu():
    GREETING_TEXT = """Welcome in 'Save film' system!
You can enter next commands:
1) Create
2) Update
3) Read
4) Delete """
    commands_container = [command.lower() for command in ["create", "update", "read", "delete"]]
    while True:
        print(GREETING_TEXT)
        command = input('Enter command: ')
        if command.lower() in commands_container:
            break
        else:
            print('You entered wrong command, try again.')
    return command

In [187]:
menu()

Welcome in 'Save film' system!
You can enter next commands:
1) Create
2) Update
3) Read
4) Delete 
Enter command: create


'create'

In [202]:
new_dict = {
    "films": {
        1: {
            "name": "Avatar",
            "director": "James Cameron"
        },
        2: {
            "name": "Harry Potter",
            "director": "Chis Colambus"
        }
    }
}

In [200]:
new_dict["films"]

{1: {'name': 'Avatar', 'director': 'James Cameron'},
 2: {'name': 'Harry Potter', 'director': 'Chis Colambus'}}

In [185]:
a = menu(some_str)
print(a)
print(type(a))

Welcome in 'Save film' system!
You can enter next commands:
1) Create
2) Update
3) Read
4) Delete 
Enter command: create
create
<class 'str'>


In [177]:
print(menu()

Welcome in 'Save film' system!
You can enter next commands:
1) Create
2) Update
3) Read
4) Delete 
Enter command: create


'create'

In [174]:
if command == "create":
    create_film()
elif command == "update":
    update_film()
elif command == "delete":
    delete_film()
elif command == "read":
    read_film()

1. Дивимось на набір полів, котрі необхідні для фільму
2. Запитуємо кожне з полів в юзера
3. Валідуємо значення цих полів
4. Якщо не валідне, запитуємо значення знову
5. Повторюємо для необов'язкових полів, якщо значення не валідне чи не введене - пропускаємо
6. Перевіряємо наявність фільму в базі

Назва: str
Жанр (опціонально): List[str], max = 3
Рік випуску: int > 0
Режисер: str, only alphabet chars
Рейтинг IMDB: float >= 0, round(2,1)
Склад акторів (опціонально): List[str]
Вікові обмеження (опціонально): str
Тривалість (опціонально): int
Мова (опціонально): str

In [193]:
# Валідатори обмежень

def validate_int(value):
    return value.isnumeric()

def validate_float():
    pass    

def validate_num():
    pass

In [195]:
# Валідатори полів

def validate_name():
    pass

def validate_year():
    return validate_int()
    
def validate_rank(rank):
    return validate_float() and rank > 0

In [190]:


mandatory_fields_list = ["name", "year", "director", "imdb"]

non_mandatory_fields_list = ["genre", "actors", "age", "duration", "language"]

for field in mandatory_fields_list:
    is_field_valid = False
    while not is_field_valid:
        field_value = input(f"Введить значення для поля {field} ")
        is_field_valid = validate(field_value)
        if not is_field_valid:
            print("Це поле не є валідним!")

Введить значення для поля name flfl
Це поле не є валідним!
Введить значення для поля name ffk
Це поле не є валідним!


KeyboardInterrupt: Interrupted by user

In [ ]:
example_film_dict = {
    "id": 2,
    "name": "Аватар: Шлях води",
    "genres": ["Action"],
    "year": 2022,
    "director": "James Cameron",
    "imdb": 7.8,
}

In [172]:
command_to_function_mapping = {
    "create": create_film,
    "update": update_film,
    "delete": delete_film,
    "read": read_film
}

Вітаю в системі для збереження даних про фільми.
Print help for help
Введіть команду: help
Вам доступні наступні команди:
1. create
2. update
3. read
4. delete
Введіть команду: create
create


In [163]:
print("""Вітаю в системі для збереження даних про фільми. 
Ви можете ввести наступні команди:""")
for number, command in enumerate(commands_container):
    print(f"{number + 1}. {command}")

Вітаю в системі для збереження даних про фільми. 
Ви можете ввести наступні команди:
1. create
2. update
3. read
4. delete


In [ ]:
[{
    "id": 3,
    "name": "Аватар: Шлях води 3",
    "genres": ["Action"],
    "year": 2022,
    "director": "James Cameron",
    "imdb": 7.8,    
},
{
    "id": 3,
    "name": "Аватар: Шлях води 3",
    "genres": ["Action"],
    "year": 2022,
    "director": "James Cameron",
    "imdb": 7.8,    
},
{
    "id": 3,
    "name": "Аватар: Шлях води 3",
    "genres": ["Action"],
    "year": 2022,
    "director": "James Cameron",
    "imdb": 7.8,    
}]

##### 

In [ ]:
#Here goes code for average rank of the film in the last dataset

In [ ]:
nested_dict = {
    "key": "value",
    "another_key":
    {
        "yet_another_key": "yet_another_value",
        "and_yet_another_key": 
        [
            {
                "i_am_tired_of_this_keys": "i_am_tired_of_this_value"
            },
            {
                "hey!": "don't soomoovat'!"
            },
            "just some random string".
            [
                "yes",
                "i", 
                "created", 
                "nested", 
                "list", 
                "in", 
                "nested", 
                "dict", 
                {
                    "with a dict": "in here!"
                }
            ]
        ]
    }
}

In [131]:
d = {'a': 10, 'b': 20, 'c': 30}

In [132]:
d.clear()

In [134]:
d

dict

In [135]:
a = {1: 2}

In [139]:
a.get(10, -1)

-1

In [ ]:
a.get(6, "Default value")

In [140]:
dict_from_compr = {key: key**2 for key in range(10, 1, -1)}

In [141]:
dict_from_compr

{10: 100, 9: 81, 8: 64, 7: 49, 6: 36, 5: 25, 4: 16, 3: 9, 2: 4}

In [ ]:
dict_from_compr.keys()

In [ ]:
dict_from_compr.values()

In [ ]:
dict_from_compr.items()

In [ ]:
dict_from_compr.pop(0)

In [143]:
dict_from_compr.pop(2, "Default value")

4

In [144]:
dict_from_compr

{10: 100, 9: 81, 8: 64, 7: 49, 6: 36, 5: 25, 4: 16, 3: 9}

In [ ]:
dict_from_compr

In [145]:
dict_from_compr.popitem()

(3, 9)

In [146]:
dict_from_compr

{10: 100, 9: 81, 8: 64, 7: 49, 6: 36, 5: 25, 4: 16}

In [147]:
DEFAULT_VALUE_ON_INCORRECT_OP = "Введи іншу операцію! Цей символ некорректний!"

a = float(input("Введи перший операнд "))
b = float(input("Введи другий операнд "))

command = input("Введи дію ")

operations_dict = {
    "+": a + b,
    "-": a - b,
    "*": a*b,
    "/": a/b if b !=0 else "Division by zero is prohibited"
}

print(operations_dict.get(command, DEFAULT_VALUE_ON_INCORRECT_OP))

Введи перший операнд 1.2
Введи другий операнд 2.0
Введи дію +
3.2


In [ ]:
print("Привіт! Ця проста програма приймає кордони значень, крок і команду, \
      що описує список, який треба згенерувати")

lower_threshold = int(input("Введи нижнє обмеження для програми"))
upper_threshold = int(input("Введи верхнє обмеження для програми"))
step = int(input("Введи крок, з яким ми будемо ітеруватися"))

command = input("Введи команду. Доступні команди: make_squares, make_cubes")

is_odd = input("Введи команду для парності числа. Введи odd для підрахунку списку для непарних\
чисел і even для парних")

commands_to_actions_mapping = {
    "make_squares": {
        "even": (i**2 for i in range(lower_threshold, upper_threshold, step) if i%2 == 0),
        "odd":  (i**2 for i in range(lower_threshold, upper_threshold, step) if i%2 == 1),
    },
    "make_cubes": {
        "even": (i**3 for i in range(lower_threshold, upper_threshold, step) if i%2 == 0),
        "odd":  (i**3 for i in range(lower_threshold, upper_threshold, step) if i%2 == 1),
    }
}

print(list(commands_to_actions_mapping[command][is_odd]))